apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubernetes.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # https://github.com/kubernetes/examples/issues/89
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: {{ template "kubernetes.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: cassandra
    - name: jmx
      port: 7199
    {{- if .Values.cassandraExporter.enabled }}
    - name: metrics
      port: 8080
      targetPort: {{ .Values.cassandraExporter.config.listenPort }}
      protocol: TCP
    - name: jmx-exporter
      port: 5555
      targetPort: 5555
    {{- end }}
  selector:
    app: {{ template "kubernetes.name" . }}