# Set where Cassandra local data should be located
cassandraNodeSelector:
  node-role.kubernetes.io/node: "true"

# Number of nodes
cassandraReplicaCount: 3
# Number of maximum dead nodes
cassandraMaxUnavailableNodes: 1

# Cassandra settings
cassandraImageName: "quay.io/mysocialapp/cassandra"
cassandraImageVersion: "3.11.4"
cassandraDC: "DC1"
cassandraConfig:
  concurrentWrites: 128
  concurrentReads: 128
  concurrentCompactors: 2
  batchSizeWarnThresholdInKb: 64
  batchSizeFailThresholdInKb: 640
  compactionThroughputMbPerSec: 150
  heapNewSize: 256M
  hintedHandoffThrottleInKb: 4096
  maxHintsDeliveryThreads: 4
  memtableAllocationType: "offheap_objects"
  memtableFlushWriter: 4
  memtableCleanupThreshold: 0.2
  rowCacheSizeInMb: 128
  rowCacheSavePeriod: 14400
cassandraMountPathPrefix: "/mnt/data"
cassandraJvmOptions: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2"
cassandraResources: {}
#  limits:
#    memory: 2400Mi
#  requests:
#    memory: 2400Mi

# Backups
cassandraBackup:
  enableBackups: false
  backupSchedule: "0 3 * * *"
  backupImageVersion: v0.1
  awsAccessKeyId: "xxx"
  awsSecretAccessKey: "yyy"
  awsPassphrase: "zzz"
  awsBucket: "bucket_name"
  #duplicityOptions: "--archive-dir /var/lib/cassandra/.duplicity --allow-source-mismatch --s3-european-buckets --s3-use-new-style --copy-links --num-retries 3 --s3-use-multiprocessing --s3-multipart-chunk-size 100 --volsize 1024 full . s3://s3.amazonaws.com/cassandra-backups/$CLUSTER_DOMAIN/$CASSANDRA_CLUSTER_NAME/$(hostname)"
  awsDestinationPath: "s3://s3-eu-west-1.amazonaws.com/${AWS_BUCKET}/$CLUSTER_DOMAIN/$CASSANDRA_CLUSTER_NAME/$(hostname)"
  restoreFolder: "/var/lib/cassandra/restore"
  removeOlderThan: "3M"

# Cassandra Exporter
cassandraExporter:
  enableExporter: false
  replicaCount: 1
  imageVersion: 2.2.1
  nodeSelector:
    node-role.kubernetes.io/node: "true"
  resources:
    limits:
      cpu: 300m
      memory: 500Mi
    requests:
      cpu: 300m
      memory: 500Mi
  config:
    host: 127.0.0.1:7199
    listenPort: 8080
    jvmOpts: ""

#Â Casspoke
casspoke:
  enablePoke: false
  imageVersion: 1.3
  replicaCount: 3
  nodeSelector:
    node-role.kubernetes.io/node: "true"
  config:
    httpServerPort: 8080
    clustername: cassandra
    host: cassandra-0.cassandra:9042,cassandra-1.cassandra:9042,cassandra-2.cassandra:9042
  envVariables:
    JVM_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:MaxRAMFraction=2 -XX:+AlwaysPreTouch"
  resources: {}
#    limits:
#      cpu: 300m
#      memory: 500Mi
#    requests:
#      cpu: 300m
#      memory: 500Mi

# Prometheus scraping
cassandraPrometheusScrap:
  enableScrap: false

# Alertmanager
cassandraAlertmanager:
  enableAlerts: false
  alertLabels:
    sloInterrupt:
      serviceLevel: objective
      severity: interrupt
      team: infra
      type: functional
    sloPage:
      serviceLevel: objective
      severity: page
      team: infra
      type: functional
  alertRules:
    cassPokeWarn: 3e+8
    cassPokeCrit: 1e+10

# Cassandra Reaper Client register
cassandraReaperRegister:
  enableReaperRegister: false
  reaperServerServiceName: cassandra-reaper.svc

# Cassandra Reaper Server
cassandraReaper:
  enableReaper: false
  replicaCount: 1
  imageVersion: 1.4.4
  nodeSelector:
    node-role.kubernetes.io/node: "true"
  contactPoints: cassandra-0.cassandra
  jmxAuth:
    username: reaperUser
    password: reaperPass
  # clusterName:
  # keyspace: reaper_db
  envVariables:
    JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -XX:+AlwaysPreTouch"
    REAPER_CASS_KEYSPACE: reaper_db
    REAPER_REPAIR_PARALELLISM: DATACENTER_AWARE
    REAPER_REPAIR_INTENSITY: 0.5
    REAPER_AUTO_SCHEDULING_ENABLED: true
    REAPER_SCHEDULE_DAYS_BETWEEN: 2
    REAPER_REPAIR_RUN_THREADS: 16
    REAPER_HANGING_REPAIR_TIMEOUT_MINS: 30
    REAPER_REPAIR_MANAGER_SCHEDULING_INTERVAL_SECONDS: 10
    REAPER_SEGMENT_COUNT: 200
    REAPER_LOGGING_ROOT_LEVEL: INFO
    REAPER_SERVER_ADMIN_PORT: 8081
    REAPER_SERVER_APP_PORT: 8080
    REAPER_METRICS_ENABLED: true
  resources: {}
#    limits:
#      cpu: 500m
#      memory: 500Mi
#    requests:
#      cpu: 500m
#      memory: 500Mi
